#!/usr/bin/env bash

VYOS_BUILD_REPO="${VYOS_BUILD_REPO:-https://github.com/vyos/vyos-build.git}"
VYOS_BRANCH="${VYOS_BRANCH:-rolling}"

vyos_source_dir() {
    printf '%s\n' "${ROOT_DIR}/cache/vyos-build"
}

vyos_fetch() {
    local dir
    dir="$(vyos_source_dir)"

    if [[ -d "${dir}/.git" ]]; then
        info "Updating VyOS build repository..."
        git -C "${dir}" fetch --depth=1 origin "${VYOS_BRANCH}"
        git -C "${dir}" reset --hard FETCH_HEAD
    else
        info "Cloning VyOS build repository..."
        rm -rf "${dir}"
        git clone \
            --depth=1 \
            --branch "${VYOS_BRANCH}" \
            "${VYOS_BUILD_REPO}" \
            "${dir}"
    fi
}

vyos_arm64_config() {
    local dir
    dir="$(vyos_source_dir)"

    local config="${dir}/scripts/package-build/linux-kernel/config/arm64/vyos_defconfig"

    [[ -f "${config}" ]] || die "VyOS ARM64 kernel config not found: ${config}"

    printf '%s\n' "${config}"
}

vyos_kernel_version() {
    local dir
    dir="$(vyos_source_dir)"

    local defaults="${dir}/data/defaults.toml"

    [[ -f "${defaults}" ]] || die "VyOS defaults.toml not found"

    grep -E 'kernel_version|linux_kernel_version' "${defaults}" | head -1
}

vyos_kernel_source_dir() {
    local version="$1"
    printf '%s\n' "${ROOT_DIR}/cache/linux-vyos/linux-${version}"
}

vyos_kernel_prepare() {
    local version="$1"

    local cache="${ROOT_DIR}/cache/linux-vyos"
    local source="${cache}/linux-${version}"
    local archive="${cache}/linux-${version}.tar.xz"
    local signature="${cache}/linux-${version}.tar.sign"
    local patch_dir
    local stamp
    local vyos_commit

    patch_dir="$(vyos_source_dir)/scripts/package-build/linux-kernel/patches/kernel"
    stamp="${source}/.vyos-kernel-prepared"
    vyos_commit="$(git -C "$(vyos_source_dir)" rev-parse HEAD)"

    if [[ -f "${stamp}" ]] &&
       grep -qx "kernel_version=${version}" "${stamp}" &&
       grep -qx "vyos_commit=${vyos_commit}" "${stamp}"; then
        info "VyOS kernel source already prepared: ${source}"
        return 0
    fi

    mkdir -p "${cache}"

    #
    # Existing trees from previous/manual builds may already contain
    # VyOS patches. Never blindly patch an unknown existing tree.
    #
    if [[ -d "${source}" ]]; then
        warn "Kernel source exists without preparation stamp."
        warn "Recreating it from the verified upstream archive."
        rm -rf "${source}"
    fi

    command -v curl >/dev/null 2>&1 ||
        die "curl is required"

    command -v gpg2 >/dev/null 2>&1 ||
        die "gpg2 is required"

    command -v xz >/dev/null 2>&1 ||
        die "xz is required"

    command -v patch >/dev/null 2>&1 ||
        die "patch is required"

    info "Fetching Linux ${version} from kernel.org..."

    if [[ ! -s "${archive}" ]]; then
        curl -fL \
            "https://www.kernel.org/pub/linux/kernel/v6.x/linux-${version}.tar.xz" \
            -o "${archive}"
    fi

    if [[ ! -s "${signature}" ]]; then
        curl -fL \
            "https://www.kernel.org/pub/linux/kernel/v6.x/linux-${version}.tar.sign" \
            -o "${signature}"
    fi

    info "Importing kernel.org signing keys..."

    gpg2 --locate-keys \
        torvalds@kernel.org \
        gregkh@kernel.org

    info "Verifying Linux ${version} source signature..."

    xz -cd "${archive}" |
        gpg2 --verify "${signature}" -

    info "Extracting Linux ${version}..."

    tar -C "${cache}" -xf "${archive}"

    [[ -d "${source}" ]] ||
        die "Kernel extraction failed: ${source}"

    [[ -d "${patch_dir}" ]] ||
        die "VyOS kernel patch directory not found: ${patch_dir}"

    info "Applying official VyOS kernel patches..."

    while IFS= read -r patch_file; do
        [[ -f "${patch_file}" ]] || continue

        info "Applying $(basename "${patch_file}")"

        patch \
            -d "${source}" \
            -p1 \
            < "${patch_file}"
    done < <(
        find "${patch_dir}" \
            -maxdepth 1 \
            -type f \
            -printf '%p\n' |
            sort
    )

    #
    # Match the VyOS kernel builder's certificate identity adjustment.
    #
    if [[ -f "${source}/certs/default_x509.genkey" ]]; then
        sed -i \
            -e 's/CN =.*/CN=VyOS Networks build time autogenerated Kernel key/' \
            "${source}/certs/default_x509.genkey"
    fi

    {
        echo "kernel_version=${version}"
        echo "vyos_branch=${VYOS_BRANCH}"
        echo "vyos_commit=${vyos_commit}"
    } > "${stamp}"

    info "VyOS kernel source prepared successfully."
}
