#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARMBIAN="${ARMBIAN:-$ROOT/cache/armbian-build}"

BOARD="${1:?Usage: $0 <board> [branch]}"
BRANCH="${2:-current}"

BOARD_CONF="$ARMBIAN/config/boards/${BOARD}.conf"

[[ -f "$BOARD_CONF" ]] || {
    echo "ERROR: Armbian board definition not found: $BOARD_CONF" >&2
    exit 1
}

get_var()
{
    local name="$1"

    sed -n \
        "s/^[[:space:]]*\(declare[[:space:]]\+-g[[:space:]]\+\)\?${name}=[\"']\?\([^\"'#]*\).*/\2/p" \
        "$BOARD_CONF" |
        head -n1 |
        sed 's/[[:space:]]*$//'
}

BOARD_NAME="$(get_var BOARD_NAME)"
BOARD_VENDOR="$(get_var BOARD_VENDOR)"
BOARDFAMILY="$(get_var BOARDFAMILY)"
BOOTCONFIG="$(get_var BOOTCONFIG)"
BOOT_FDT_FILE="$(get_var BOOT_FDT_FILE)"
BOOT_SCENARIO="$(get_var BOOT_SCENARIO)"
BOOT_SOC="$(get_var BOOT_SOC)"
IMAGE_PARTITION_TABLE="$(get_var IMAGE_PARTITION_TABLE)"

OUT="$ROOT/work/build/$BOARD/boot"
ARTIFACTS="$OUT/artifacts"

rm -rf "$OUT"
mkdir -p "$ARTIFACTS"

BOOT_BACKEND=""
REQUIRES_UBOOT=no
REQUIRES_ATF=no
REQUIRES_DDR_BLOB=no

UBOOT_SOURCE=""
UBOOT_BRANCH=""
DDR_BLOB=""
BL31_BLOB=""

BOOTLOADER_IMAGE_1=""
BOOTLOADER_OFFSET_1=""
BOOTLOADER_IMAGE_2=""
BOOTLOADER_OFFSET_2=""

case "${BOARDFAMILY}:${BRANCH}" in

    rockchip-rk3588:current)

        #
        # Armbian rockchip-rk3588 current:
        #
        #   BOOTSOURCE = Radxa U-Boot
        #   BOOT_SCENARIO = spl-blobs
        #
        # Result:
        #   idbloader.img @ sector 64
        #   u-boot.itb    @ sector 16384
        #
        # dd uses its default 512-byte block size here.
        #

        BOOT_BACKEND="rockchip-idb-itb"
        BOOT_SCENARIO="${BOOT_SCENARIO:-spl-blobs}"
        BOOT_SOC="${BOOT_SOC:-rk3588}"

        UBOOT_SOURCE="https://github.com/radxa/u-boot.git"
        UBOOT_BRANCH="branch:next-dev-v2024.10"

        DDR_BLOB="rk35/rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.20_20250926.bin"
        BL31_BLOB="rk35/rk3588_bl31_v1.48.elf"

        BOOTLOADER_IMAGE_1="idbloader.img"
        BOOTLOADER_OFFSET_1=32768

        BOOTLOADER_IMAGE_2="u-boot.itb"
        BOOTLOADER_OFFSET_2=8388608

        REQUIRES_UBOOT=yes
        REQUIRES_ATF=yes
        REQUIRES_DDR_BLOB=yes
        ;;

    *)
        echo "ERROR: unsupported bootchain: ${BOARDFAMILY}/${BRANCH}" >&2
        exit 1
        ;;
esac

MANIFEST="$OUT/boot-manifest.env"

cat > "$MANIFEST" <<EOF_MANIFEST
# Generated by tools/resolve-bootchain.sh
# Do not edit manually.

BOARD=$BOARD
BOARD_NAME=$BOARD_NAME
BOARD_VENDOR=$BOARD_VENDOR
BOARD_FAMILY=$BOARDFAMILY
BRANCH=$BRANCH

BOOT_BACKEND=$BOOT_BACKEND
BOOT_SCENARIO=$BOOT_SCENARIO
BOOT_SOC=$BOOT_SOC
PARTITION_TABLE=${IMAGE_PARTITION_TABLE:-gpt}

BOOTCONFIG=$BOOTCONFIG
BOOT_FDT_FILE=$BOOT_FDT_FILE

UBOOT_SOURCE=$UBOOT_SOURCE
UBOOT_BRANCH=$UBOOT_BRANCH

DDR_BLOB=$DDR_BLOB
BL31_BLOB=$BL31_BLOB

BOOTLOADER_IMAGE_1=$BOOTLOADER_IMAGE_1
BOOTLOADER_OFFSET_1=$BOOTLOADER_OFFSET_1

BOOTLOADER_IMAGE_2=$BOOTLOADER_IMAGE_2
BOOTLOADER_OFFSET_2=$BOOTLOADER_OFFSET_2

REQUIRES_UBOOT=$REQUIRES_UBOOT
REQUIRES_ATF=$REQUIRES_ATF
REQUIRES_DDR_BLOB=$REQUIRES_DDR_BLOB
EOF_MANIFEST

cat > "$OUT/boot-manifest.txt" <<EOF_TEXT
Board:              $BOARD_NAME
Vendor:             $BOARD_VENDOR
Family:             $BOARDFAMILY
Branch:             $BRANCH

Backend:            $BOOT_BACKEND
Scenario:           $BOOT_SCENARIO
SoC:                $BOOT_SOC
Partition table:    ${IMAGE_PARTITION_TABLE:-gpt}

U-Boot config:      $BOOTCONFIG
U-Boot source:      $UBOOT_SOURCE
U-Boot branch:      $UBOOT_BRANCH

DDR blob:           $DDR_BLOB
BL31 blob:          $BL31_BLOB

Artifact 1:         $BOOTLOADER_IMAGE_1
Offset 1:           $BOOTLOADER_OFFSET_1 bytes

Artifact 2:         $BOOTLOADER_IMAGE_2
Offset 2:           $BOOTLOADER_OFFSET_2 bytes

DTB:                $BOOT_FDT_FILE

Needs U-Boot:       $REQUIRES_UBOOT
Needs ATF/BL31:     $REQUIRES_ATF
Needs DDR blob:     $REQUIRES_DDR_BLOB
EOF_TEXT

echo "Bootchain resolved:"
echo
cat "$OUT/boot-manifest.txt"
echo
echo "Manifest:"
echo "  $MANIFEST"
